### ISSUE TITLE
google play can not find gmission app,can you send gmission app to me by e-mail?

### ISSUE THREAD

**Issue by JunjieChen-2020** [gmission/gmission_reborn_android#1]
Hi, I can not find  gmission app in google play and the link,can you send gmission app to me by e-mail?
xyq062446@163.com
thank you.

**Comment by chenzhao** [comment]
> Hi, I can not find gmission app in google play and the link,can you send gmission app to me by e-mail? [xyq062446@163.com](mailto:xyq062446@163.com) thank you.

The android developer left the group several years ago. So we cannot provide any help on the android client now.  I suggest you compile it with the current android sdk to see if it still works. Good luck.
